### PR TITLE
Update dc_wol.json

### PR DESCRIPTION
**Pull request by Scarpetta26**

### CODE REVIEW

**Comment by Scarpetta26** [comment]
Hey. I'm going to do a massive update for the app at the beginning of
February.  Can you create a folder for trinity war for me.  And I'll add
the constructs to the war of light folder.

Let me know.  Thanks

**Comment by Kyrremann** [comment]
I'm guessing you really mean file, and not folder?! Anywho, I've added the Trinity War file in the assets folder here: https://github.com/Kyrremann/ClixEmAll/blob/master/assets/dc_jltw.json, and you can add the WOL constructs in the dc_wol.json.

**Comment by Scarpetta26** [comment]
Yes i meant file.  I appreciate it.  I also need to update the new hobbit
set too.  I forgot to mention that earlier.  If you would kindly create a
file for that as well.  I should update all of it around the 6th or 7th of
Feb.  Just wanted to give you a heads up.

**Comment by Kyrremann** [comment]
Sounds good, I've added a file for the set The Hobbit: The Battle of the Five Armies now.

**Comment by Scarpetta26** [comment]
I created a pull request for trinity war.  It also has the fast forces in
it as well.  If you could make a file for that too and move it over.  Thanks

**Comment by Kyrremann** [comment]
I've posted some comments on your commit, as you haven't made a pull request yet :)

**Pull request merged**
