### PR TITLE
Update dc_jltw.json

### PR DESCRIPTION
**Pull request by Scarpetta26**

### CODE REVIEW

**Comment by Scarpetta26** [comment]
When will you be able to update the app on the store?

**Comment by Kyrremann** [comment]
Hopefully tonight :)

**Comment by Scarpetta26** [comment]
Sweet.  Thanks for everything.  It's kinda cool to collaborate on something
like this with someone i don't know.  :)

**Comment by Kyrremann** [comment]
It should now be up.
And yeah, that's true.

**Pull request merged**
